### ISSUE TITLE
Remove redundant data

### ISSUE THREAD

**Issue by pilcrowonpaper** [saladbowl77/heatstroke-site#1]
この[ツイート](https://twitter.com/pilcrowonpaper/status/1550402108737736704)でいいねしてくれた人を見たら日本人がいたので、ブログとか色々見て、ここまできました。`routes/graph.svelte` に

```js
// 二重になってるので一つに統一したい
const prefData = [...]
const prefDB = {...}
```

とあったのですが、都道府県は配列に保存すれば良いのでは？[REPL](https://svelte.dev/repl/16a294c19d1d43e78c95778bbba6fdda?version=3.49.0)

あ、あと同じく高校生です！

**Comment by saladbowl77** [comment]
Thankyou Issue!!

一応この分かれてしまった理由が、SelectのOptionを作るための配列と都道府県IDと都道府県名を一致させるDBとして使いたかったからなんですね。
配列に保存してもいいのですが、結局は`prefID`と都道府県名を一致させるために`const prefDB = {...}`は必須になってくるので、あまりメリットがないかもしれません。

するのであれば`prefDB`をselectの方にやって`selectedPrefectureIndex`で取れたらいんですけどね...


高校生ですか!!
とても英語がお上手ですが英語圏に住んでいたんですか?

**Comment by pilcrowonpaper** [comment]
となると、
- Object を使う [REPL](https://svelte.dev/repl/51d9d335fcfb48ac953513634afdbbb4?version=3.49.0)
- Map を使う [REPL](https://svelte.dev/repl/b402669929c24fbea32f858b51bb8802?version=3.49.0)

Edit: 
あ、忘れてました
アメリカ+シンガポール８年間住んでました

**Comment by saladbowl77** [comment]
Map使う方法もあるんですね...
どちらの方がベストなのか微妙ですが、今あるのを流用できるっていう面ではObjectの方が楽そう..?
もしよかったら、変更したコードでプルリクしていただいてもいいですか..?
せっかく提案いただいて例示もしていただいてるので...

すごい。めちゃめちゃ住まれてますね。
Twitterフォローしときました
とてもイラスト上手ですね。
